/**
* Nekos API
* An open source anime artworks API.
*
* OpenAPI spec version: v3
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package news.models

import kotlinx.serialization.Serializable






import kotlinx.serialization.SerialName


/**
 * 
 * @param id The tag's ID.
 * @param idV2 The tag's ID in the v2 API. Format: UUID
 * @param name The tag's name.
 * @param description A short description that says what the tag is and when it applies.
 * @param sub The subtype of the tag (format, character, setting).
 * @param isNsfw Whether the tag is NSFW or not (usually, tags with this set to true will only be on NSFW images).
 */
@Serializable
internal data class TagSchema (
    /* The tag's ID. */
    
    @SerialName("id")
    val id: kotlin.Int,
    /* The tag's ID in the v2 API. Format: UUID */
    
    @SerialName("id_v2")
    val idV2: kotlin.String,
    /* The tag's name. */
    
    @SerialName("name")
    val name: kotlin.String,
    /* A short description that says what the tag is and when it applies. */
    
    @SerialName("description")
    val description: kotlin.String,
    /* The subtype of the tag (format, character, setting). */
    
    @SerialName("sub")
    val sub: kotlin.String,
    /* Whether the tag is NSFW or not (usually, tags with this set to true will only be on NSFW images). */
    
    @SerialName("is_nsfw")
    val isNsfw: kotlin.Boolean

) {

}

